<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <CompressionEnabled>false</CompressionEnabled>
    </PropertyGroup>

    <PropertyGroup Label="Nuget Settings">
        <PackageId>MoonlightServers.Frontend</PackageId>
        <Title>MoonlightServers.Frontend</Title>
        <Version>2.1.0</Version>
        <IsPackable>true</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.9" />
        <PackageReference Include="Moonlight.Client" Version="2.1.*"/>
        <PackageReference Include="XtermBlazor" Version="2.1.2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\MoonlightServers.Shared\MoonlightServers.Shared.csproj"/>
    </ItemGroup>

    <ItemGroup Label="Build instruction for nuget package building">
        <Compile Remove="storage\**\*" />
        <Content Remove="storage\**\*" />
        <None Remove="storage\**\*" />
    </ItemGroup>

    <ItemGroup>
        <None Include="Styles/mappings/*.map" Pack="true" PackagePath="Styles/" />
        <None Include="MoonlightServers.Frontend.targets" Pack="true" PackagePath="build/MoonlightServers.Frontend.targets" />
    </ItemGroup>

</Project>
