<Project>
    <ItemGroup>
        <StylesFilesToCopy Include="$(MSBuildThisFileDirectory)../Styles/**/*.*"/>
    </ItemGroup>
    <Target Name="CopyContent" BeforeTargets="Build">
        <Copy SourceFiles="@(StylesFilesToCopy)" DestinationFolder="$(ProjectDir)Styles/MoonlightServers.Frontend/%(RecursiveDir)" SkipUnchangedFiles="true" />
    </Target>
</Project>