<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup Label="Nuget Settings">
        <Title>MoonlightServers.DaemonShared</Title>
        <PackageId>MoonlightServers.DaemonShared</PackageId>
        <Version>2.1.0</Version>
        <PackageTags>shared</PackageTags>
        <IsPackable>true</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="DaemonSide\Http\Responses\Servers\Files\"/>
    </ItemGroup>

</Project>
