<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Docker.DotNet" Version="3.125.15" />
        <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.1.0" />
        <PackageReference Include="MoonCore" Version="1.8.3" />
        <PackageReference Include="MoonCore.Extended" Version="1.2.8" />
        <PackageReference Include="MoonCore.Unix" Version="1.0.2" />
        <PackageReference Include="Stateless" Version="5.17.0" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2"/>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Http\Middleware\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\MoonlightServers.DaemonShared\MoonlightServers.DaemonShared.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="data\**" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Remove="data\**" />
    </ItemGroup>

    <ItemGroup>
      <Content Remove="data\**" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="data\**" />
    </ItemGroup>

</Project>
