<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>
    
    <PropertyGroup Label="Nuget Settings">
        <PackageId>MoonlightServers.ApiServer</PackageId>
        <Title>MoonlightServers.ApiServer</Title>
        <Version>2.1.0</Version>
        <IsPackable>true</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Moonlight.ApiServer" Version="2.1.*" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.7"/>
        <PackageReference Include="Riok.Mapperly" Version="4.3.0-next.2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\MoonlightServers.DaemonShared\MoonlightServers.DaemonShared.csproj"/>
        <ProjectReference Include="..\MoonlightServers.Shared\MoonlightServers.Shared.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Database\Migrations\"/>
        <Folder Include="Http\Middleware\"/>
    </ItemGroup>

    <ItemGroup Label="Build instruction for nuget package building">
        <Compile Remove="storage\**\*"/>
        <Content Remove="storage\**\*"/>
        <None Remove="storage\**\*"/>
    </ItemGroup>

</Project>
