<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Moonlight.ApiServer" Version="2.1.0"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11"/>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\MoonlightServers.Frontend\MoonlightServers.Frontend.csproj"/>
        <ProjectReference Include="..\MoonlightServers.Shared\MoonlightServers.Shared.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Database\Migrations\"/>
        <Folder Include="Helpers\"/>
        <Folder Include="Http\Controllers\" />
        <Folder Include="Http\Middleware\"/>
        <Folder Include="Implementations\"/>
        <Folder Include="Interfaces\"/>
        <Folder Include="Models\"/>
    </ItemGroup>

</Project>
