<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup Label="Nuget Settings">
        <PackageId>MoonlightServers.Shared</PackageId>
        <Title>MoonlightServers.Shared</Title>
        <Version>2.1.0</Version>
        <PackageTags>shared</PackageTags>
        <IsPackable>true</IsPackable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Http\Responses\Users\Servers\" />
    </ItemGroup>
    
</Project>
