// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoonlightServers.ApiServer.Database;

#nullable disable

namespace MoonlightServers.ApiServer.Database.Migrations
{
    [DbContext(typeof(ServersDataContext))]
    [Migration("20241215151257_AddedServerRelations")]
    partial class AddedServerRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Servers")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MoonlightServers.ApiServer.Database.Entities.Allocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NodeId")
                        .HasColumnType("int");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<int?>("ServerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("ServerId");

                    b.ToTable("Allocations", "Servers");
                });

            modelBuilder.Entity("MoonlightServers.ApiServer.Database.Entities.Node", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EnableDynamicFirewall")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EnableTransparentMode")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Fqdn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("FtpPort")
                        .HasColumnType("int");

                    b.Property<int>("HttpPort")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("UseSsl")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Nodes", "Servers");
                });

            modelBuilder.Entity("MoonlightServers.ApiServer.Database.Entities.Server", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Bandwidth")
                        .HasColumnType("int");

                    b.Property<int>("Cpu")
                        .HasColumnType("int");

                    b.Property<int>("Disk")
                        .HasColumnType("int");

                    b.Property<int>("DockerImageIndex")
                        .HasColumnType("int");

                    b.Property<int>("Memory")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NodeId")
                        .HasColumnType("int");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int>("StarId")
                        .HasColumnType("int");

                    b.Property<string>("StartupOverride")
                        .HasColumnType("longtext");

                    b.Property<bool>("UseVirtualDisk")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("StarId");

                    b.ToTable("Servers", "Servers");
                });

            modelBuilder.Entity("MoonlightServers.ApiServer.Database.Entities.ServerBackup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Completed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ServerId")
                        .HasColumnType("int");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<bool>("Successful")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.ToTable("ServerBackups", "Servers");
                });

            modelBuilder.Entity("MoonlightServers.ApiServer.Database.Entities.ServerVariable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ServerId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.ToTable("ServerVariables", "Servers");
                });

            modelBuilder.Entity("MoonlightServers.ApiServer.Database.Entities.Star", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowDockerImageChange")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DefaultDockerImage")
                        .HasColumnType("int");

                    b.Property<string>("DonateUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("InstallDockerImage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("InstallScript")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("InstallShell")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OnlineDetection")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ParseConfiguration")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RequiredAllocations")
                        .HasColumnType("int");

                    b.Property<string>("StartupCommand")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StopCommand")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UpdateUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Stars", "Servers");
                });

            modelBuilder.Entity("MoonlightServers.ApiServer.Database.Entities.StarDockerImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoPulling")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StarId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StarId");

                    b.ToTable("StarDockerImages", "Servers");
                });

            modelBuilder.Entity("MoonlightServers.ApiServer.Database.Entities.StarVariable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowEditing")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AllowViewing")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("DefaultValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Filter")
                        .HasColumnType("longtext");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StarId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StarId");

                    b.ToTable("StarVariables", "Servers");
                });

            modelBuilder.Entity("MoonlightServers.ApiServer.Database.Entities.Allocation", b =>
                {
                    b.HasOne("MoonlightServers.ApiServer.Database.Entities.Node", "Node")
                        .WithMany("Allocations")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoonlightServers.ApiServer.Database.Entities.Server", "Server")
                        .WithMany("Allocations")
                        .HasForeignKey("ServerId");

                    b.Navigation("Node");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("MoonlightServers.ApiServer.Database.Entities.Server", b =>
                {
                    b.HasOne("MoonlightServers.ApiServer.Database.Entities.Node", "Node")
                        .WithMany("Servers")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoonlightServers.ApiServer.Database.Entities.Star", "Star")
                        .WithMany()
                        .HasForeignKey("StarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");

                    b.Navigation("Star");
                });

            modelBuilder.Entity("MoonlightServers.ApiServer.Database.Entities.ServerBackup", b =>
                {
                    b.HasOne("MoonlightServers.ApiServer.Database.Entities.Server", null)
                        .WithMany("Backups")
                        .HasForeignKey("ServerId");
                });

            modelBuilder.Entity("MoonlightServers.ApiServer.Database.Entities.ServerVariable", b =>
                {
                    b.HasOne("MoonlightServers.ApiServer.Database.Entities.Server", "Server")
                        .WithMany("Variables")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("MoonlightServers.ApiServer.Database.Entities.StarDockerImage", b =>
                {
                    b.HasOne("MoonlightServers.ApiServer.Database.Entities.Star", "Star")
                        .WithMany("DockerImages")
                        .HasForeignKey("StarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Star");
                });

            modelBuilder.Entity("MoonlightServers.ApiServer.Database.Entities.StarVariable", b =>
                {
                    b.HasOne("MoonlightServers.ApiServer.Database.Entities.Star", "Star")
                        .WithMany("Variables")
                        .HasForeignKey("StarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Star");
                });

            modelBuilder.Entity("MoonlightServers.ApiServer.Database.Entities.Node", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("Servers");
                });

            modelBuilder.Entity("MoonlightServers.ApiServer.Database.Entities.Server", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("Backups");

                    b.Navigation("Variables");
                });

            modelBuilder.Entity("MoonlightServers.ApiServer.Database.Entities.Star", b =>
                {
                    b.Navigation("DockerImages");

                    b.Navigation("Variables");
                });
#pragma warning restore 612, 618
        }
    }
}
