// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoonlightServers.ApiServer.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MoonlightServers.ApiServer.Database.Migrations
{
    [DbContext(typeof(ServersDataContext))]
    [Migration("20250922091731_RecreatedModelsInNewSchema")]
    partial class RecreatedModelsInNewSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("servers")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MoonlightServers.ApiServer.Database.Entities.Allocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NodeId")
                        .HasColumnType("integer");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<int?>("ServerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("ServerId");

                    b.ToTable("Allocations", "servers");
                });

            modelBuilder.Entity("MoonlightServers.ApiServer.Database.Entities.Node", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Fqdn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FtpPort")
                        .HasColumnType("integer");

                    b.Property<int>("HttpPort")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TokenId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("UseSsl")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Nodes", "servers");
                });

            modelBuilder.Entity("MoonlightServers.ApiServer.Database.Entities.Server", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cpu")
                        .HasColumnType("integer");

                    b.Property<int>("Disk")
                        .HasColumnType("integer");

                    b.Property<int>("DockerImageIndex")
                        .HasColumnType("integer");

                    b.Property<int>("Memory")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NodeId")
                        .HasColumnType("integer");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<int>("StarId")
                        .HasColumnType("integer");

                    b.Property<string>("StartupOverride")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("StarId");

                    b.ToTable("Servers", "servers");
                });

            modelBuilder.Entity("MoonlightServers.ApiServer.Database.Entities.ServerBackup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ServerId")
                        .HasColumnType("integer");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<bool>("Successful")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.ToTable("ServerBackups", "servers");
                });

            modelBuilder.Entity("MoonlightServers.ApiServer.Database.Entities.ServerShare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ServerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.ToTable("ServerShares", "servers");
                });

            modelBuilder.Entity("MoonlightServers.ApiServer.Database.Entities.ServerVariable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ServerId")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.ToTable("ServerVariables", "servers");
                });

            modelBuilder.Entity("MoonlightServers.ApiServer.Database.Entities.Star", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowDockerImageChange")
                        .HasColumnType("boolean");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DefaultDockerImage")
                        .HasColumnType("integer");

                    b.Property<string>("DonateUrl")
                        .HasColumnType("text");

                    b.Property<string>("InstallDockerImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InstallScript")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InstallShell")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OnlineDetection")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParseConfiguration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RequiredAllocations")
                        .HasColumnType("integer");

                    b.Property<string>("StartupCommand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StopCommand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdateUrl")
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Stars", "servers");
                });

            modelBuilder.Entity("MoonlightServers.ApiServer.Database.Entities.StarDockerImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoPulling")
                        .HasColumnType("boolean");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StarId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StarId");

                    b.ToTable("StarDockerImages", "servers");
                });

            modelBuilder.Entity("MoonlightServers.ApiServer.Database.Entities.StarVariable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowEditing")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowViewing")
                        .HasColumnType("boolean");

                    b.Property<string>("DefaultValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Filter")
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StarId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StarId");

                    b.ToTable("StarVariables", "servers");
                });

            modelBuilder.Entity("MoonlightServers.ApiServer.Database.Entities.Allocation", b =>
                {
                    b.HasOne("MoonlightServers.ApiServer.Database.Entities.Node", "Node")
                        .WithMany("Allocations")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoonlightServers.ApiServer.Database.Entities.Server", "Server")
                        .WithMany("Allocations")
                        .HasForeignKey("ServerId");

                    b.Navigation("Node");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("MoonlightServers.ApiServer.Database.Entities.Server", b =>
                {
                    b.HasOne("MoonlightServers.ApiServer.Database.Entities.Node", "Node")
                        .WithMany("Servers")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoonlightServers.ApiServer.Database.Entities.Star", "Star")
                        .WithMany()
                        .HasForeignKey("StarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");

                    b.Navigation("Star");
                });

            modelBuilder.Entity("MoonlightServers.ApiServer.Database.Entities.ServerBackup", b =>
                {
                    b.HasOne("MoonlightServers.ApiServer.Database.Entities.Server", null)
                        .WithMany("Backups")
                        .HasForeignKey("ServerId");
                });

            modelBuilder.Entity("MoonlightServers.ApiServer.Database.Entities.ServerShare", b =>
                {
                    b.HasOne("MoonlightServers.ApiServer.Database.Entities.Server", "Server")
                        .WithMany("Shares")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MoonlightServers.ApiServer.Models.ServerShareContent", "Content", b1 =>
                        {
                            b1.Property<int>("ServerShareId")
                                .HasColumnType("integer");

                            b1.HasKey("ServerShareId");

                            b1.ToTable("ServerShares", "servers");

                            b1.ToJson("Content");

                            b1.WithOwner()
                                .HasForeignKey("ServerShareId");

                            b1.OwnsMany("MoonlightServers.ApiServer.Models.ServerShareContent+SharePermission", "Permissions", b2 =>
                                {
                                    b2.Property<int>("ServerShareContentServerShareId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("Identifier")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<int>("Level")
                                        .HasColumnType("integer");

                                    b2.HasKey("ServerShareContentServerShareId", "__synthesizedOrdinal");

                                    b2.ToTable("ServerShares", "servers");

                                    b2.WithOwner()
                                        .HasForeignKey("ServerShareContentServerShareId");
                                });

                            b1.Navigation("Permissions");
                        });

                    b.Navigation("Content")
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("MoonlightServers.ApiServer.Database.Entities.ServerVariable", b =>
                {
                    b.HasOne("MoonlightServers.ApiServer.Database.Entities.Server", "Server")
                        .WithMany("Variables")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("MoonlightServers.ApiServer.Database.Entities.StarDockerImage", b =>
                {
                    b.HasOne("MoonlightServers.ApiServer.Database.Entities.Star", "Star")
                        .WithMany("DockerImages")
                        .HasForeignKey("StarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Star");
                });

            modelBuilder.Entity("MoonlightServers.ApiServer.Database.Entities.StarVariable", b =>
                {
                    b.HasOne("MoonlightServers.ApiServer.Database.Entities.Star", "Star")
                        .WithMany("Variables")
                        .HasForeignKey("StarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Star");
                });

            modelBuilder.Entity("MoonlightServers.ApiServer.Database.Entities.Node", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("Servers");
                });

            modelBuilder.Entity("MoonlightServers.ApiServer.Database.Entities.Server", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("Backups");

                    b.Navigation("Shares");

                    b.Navigation("Variables");
                });

            modelBuilder.Entity("MoonlightServers.ApiServer.Database.Entities.Star", b =>
                {
                    b.Navigation("DockerImages");

                    b.Navigation("Variables");
                });
#pragma warning restore 612, 618
        }
    }
}
